# Use an official Node.js runtime as a parent image
FROM node:lts-alpine as build
#FROM node:14-alpine as build # recommended by chatgpt

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY storage-react/package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY storage-react/. .

# Build the app for production
RUN npm run build

# Use an official Nginx runtime as a parent image
FROM nginx:stable-alpine

# Copy the built React app from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Copy the nginx.conf file
COPY react/nginx.conf.prod /etc/nginx/conf.d/default.conf

# Expose port - same as in nginx.conf
EXPOSE $PORT_REACT_FRONTEND_INSIDE_CONTAINER

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
