services:
  fastapibackend:
    build: fastapi
    mem_limit: 1024m
    ports:
      - "${PORT_PYTHON_BACKEND}:8000"
    restart: on-failure
    volumes:
      - ./storage-fastapi-backend:/app
      - ./storage-common:/storage
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DB_PASS: ${AWS_DB_PASS}
      NODE_ENV: "local"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin.config.php:/etc/phpmyadmin/config.inc.php
      - ./phpmyadmin.php.ini:/usr/local/etc/php/php.ini-production
      - ./phpmyadmin.php.ini:/usr/local/etc/php/php.ini
    environment:
      - PMA_HOST=db.kamba.me
      - PMA_ARBITRARY=1