services:
  reactfrontend:
    build:
      context: ./storage-react
      dockerfile: ../react/Dockerfile.${BUILD_REACT_FRONTEND}
      args:
        - PORT_REACT_FRONTEND_INSIDE_CONTAINER=${PORT_REACT_FRONTEND_INSIDE_CONTAINER}
    volumes:
      - ./storage-react:/app
      - ./storage-common:/storage
    mem_limit: ${MEMORY_LIMIT_REACT}
    environment:
      WDS_SOCKET_PORT: ${PORT_REACT_FRONTEND_INSIDE_CONTAINER}
    ports:
      - "${PORT_REACT_FRONTEND}:${PORT_REACT_FRONTEND_INSIDE_CONTAINER}"
      - "${PORT_REACT_FRONTEND_2}:${PORT_REACT_FRONTEND_INSIDE_CONTAINER}" # leave it here! without it hot reload won't work
    command: sh -c "npm install && npm start"
    restart: on-failure
  fastapibackend:
    build: fastapi
    mem_limit: 1024m
    ports:
      - "${PORT_PYTHON_BACKEND}:8000"
    restart: on-failure
    volumes:
      - ./storage-fastapi-backend:/app
      - ./storage-common:/storage
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DB_PASS: ${AWS_DB_PASS}
      MY_AUTH_TOKEN: ${MY_AUTH_TOKEN}
      NODE_ENV: "local"

