services:
  fastapibackend:
    build: fastapi
    mem_limit: 1024m
    ports:
      - "${PORT_PYTHON_BACKEND}:8000"
    restart: on-failure
    volumes:
      - ./storage-fastapi-backend:/app
      - ./storage-common:/storage
      - ~/.garmin_session:/root/.garmin_session
      - ~/.withings_user.json:/root/.withings_user.json
      - ~/withings_app.json:/root/withings_app.json
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      ELEVEN_API_KEY: ${ELEVEN_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DB_PASS: ${AWS_DB_PASS}
      MY_AUTH_TOKEN: ${MY_AUTH_TOKEN}
      MY_AUTH_BEARER_TOKEN: ${MY_AUTH_BEARER_TOKEN}
      NODE_ENV: "local"
      TZ: Europe/Madrid
