services:
  frontend:
    build: storage-react
    container_name: frontend_c
    mem_limit: ${MEMORY_LIMIT_REACT}
    ports:
      - "${PORT_REACT_FRONTEND}:${PORT_REACT_FRONTEND_INSIDE_CONTAINER}"
      - "${PORT_REACT_FRONTEND_2}:${PORT_REACT_FRONTEND_INSIDE_CONTAINER}"
    volumes:
      - ./storage-react:/app
      - /app/node_modules
    environment:
      MY_AUTH_TOKEN: ${MY_AUTH_TOKEN}
      NODE_ENV: ${NODE_ENV}
