services:
  reactfrontend:
    build: react
    volumes:
      - ./storage-react:/app
      - ./storage-common:/storage
    mem_limit: ${MEMORY_LIMIT_REACT}
    environment:
      WDS_SOCKET_PORT: ${PORT_REACT_FRONTEND_INSIDE_CONTAINER}
    ports:
      - "${PORT_REACT_FRONTEND}:${PORT_REACT_FRONTEND_INSIDE_CONTAINER}"
      - "${PORT_REACT_FRONTEND_2}:${PORT_REACT_FRONTEND_INSIDE_CONTAINER}" # leave it here! without it hot reload won't work
    command: sh -c "npm start"
    restart: on-failure
