# test_data.py
# those are real responses from garmin API
# separated to external file - because sometimes test data is huuuuuge

TEST_DATA = {
    "get_sleep_data": {
        "dailySleepDTO": {
            "id": 1717790546000, "userProfilePK": 9813851, "calendarDate": "2024-06-08", "sleepTimeSeconds": 26040, "napTimeSeconds": 0, "sleepWindowConfirmed": True, "sleepWindowConfirmationType": "enhanced_confirmed_final", "sleepStartTimestampGMT": 1717790546000, "sleepEndTimestampGMT": 1717817126000, "sleepStartTimestampLocal": 1717797746000, "sleepEndTimestampLocal": 1717824326000, "autoSleepStartTimestampGMT": None, "autoSleepEndTimestampGMT": None, "sleepQualityTypePK": None, "sleepResultTypePK": None, "unmeasurableSleepSeconds": 0, "deepSleepSeconds": 4020, "lightSleepSeconds": 17520, "remSleepSeconds": 4500, "awakeSleepSeconds": 540, "deviceRemCapable": True, "retro": False, "sleepFromDevice": True, "averageRespirationValue": 16.0, "lowestRespirationValue": 13.0, "highestRespirationValue": 21.0, "awakeCount": 1, "avgSleepStress": 14.0, "ageGroup": "ADULT", "sleepScoreFeedback": "POSITIVE_LONG_AND_CONTINUOUS", "sleepScoreInsight": "POSITIVE_RESTFUL_EVENING", "sleepScorePersonalizedInsight": "RHYTHM_POS_GOOD_SLEEP_EXCELLENT_TIMING", "sleepScores": {"totalDuration": {"qualifierKey": "GOOD", "optimalStart": 28200.0, "optimalEnd": 28200.0}, "stress": {"qualifierKey": "GOOD", "optimalStart": 0.0, "optimalEnd": 15.0}, "awakeCount": {"qualifierKey": "EXCELLENT", "optimalStart": 0.0, "optimalEnd": 1.0}, "overall": {"value": 84, "qualifierKey": "GOOD"}, "remPercentage": {"value": 17, "qualifierKey": "FAIR", "optimalStart": 21.0, "optimalEnd": 31.0, "idealStartInSeconds": 5468.4, "idealEndInSeconds": 8072.4}, "restlessness": {"qualifierKey": "GOOD", "optimalStart": 0.0, "optimalEnd": 5.0}, "lightPercentage": {"value": 67, "qualifierKey": "FAIR", "optimalStart": 30.0, "optimalEnd": 64.0, "idealStartInSeconds": 7812.0, "idealEndInSeconds": 16665.6}, "deepPercentage": {"value": 15, "qualifierKey": "FAIR", "optimalStart": 16.0, "optimalEnd": 33.0, "idealStartInSeconds": 4166.4, "idealEndInSeconds": 8593.2}}, "sleepVersion": 2, "sleepNeed": {"userProfilePk": 9813851, "calendarDate": "2024-06-08", "deviceId": 3443617346, "timestampGmt": "2024-06-07T04:28:27", "baseline": 470, "actual": 540, "feedback": "HIGHLY_INCREASED", "trainingFeedback": "NO_CHANGE", "sleepHistoryAdjustment": "INCREASING", "hrvAdjustment": "INCREASING", "napAdjustment": "NO_CHANGE", "displayedForTheDay": True, "preferredActivityTracker": True}, "nextSleepNeed": {"userProfilePk": 9813851, "calendarDate": "2024-06-09", "deviceId": 3443617346, "timestampGmt": "2024-06-08T04:28:56", "baseline": 470, "actual": 500, "feedback": "INCREASED", "trainingFeedback": "NO_CHANGE", "sleepHistoryAdjustment": "INCREASING", "hrvAdjustment": "INCREASING", "napAdjustment": "NO_CHANGE", "displayedForTheDay": True, "preferredActivityTracker": True}, "remSleepData": True, "restlessMomentsCount": 39, "avgOvernightHrv": 53.0, "hrvStatus": "UNBALANCED", "bodyBatteryChange": 0, "restingHeartRate": 45
        }
    }
}
